name: Nix Flake Check

on: 
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with: 
          nix_path: nixpkgs=channel:nixos-unstable

        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = ${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
      - run: nix flake check
